name: sivo_suppliers
description: "Sivo Suppliers App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter:
  flutter_polyline_points: ^2.1.0
  win32: ^5.5.4
  geolocator: ^9.0.0
  geocoding: ^2.0.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  get: ^4.6.6
  flutter_vector_icons: ^2.0.0
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  flutter_hooks: ^0.20.3
  cloud_firestore:  ^4.17.5
  http: ^1.1.0
  shimmer: ^3.0.0
  glass: ^1.0.2+1
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  get_storage: ^2.1.1
  image_picker: ^1.0.4
  firebase_storage: ^11.5.3
  firebase_core: ^2.24.2
  firebase_database: ^10.3.8
  device_preview: ^1.1.0
  otp_text_field: ^1.1.3
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.2.2
  firebase_messaging: ^14.7.21
  pull_to_refresh: ^2.0.0
  location: ^7.0.0
  syncfusion_flutter_charts: ^21.1.31
  photo_view: ^0.15.0
#  package_info: ^2.0.2
  package_info_plus: 8.1.0
  dio: ^5.5.0+1
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  flutter_easyloading: ^3.0.5
  file_picker: ^8.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/anime/
    - assets/icons/
    - .env.development
    - .env.production

